trigger:
  batch: false
  branches:
    include:
      - refs/heads/main
      - main
  paths:
    include:
      - PaymentService/**
    exclude:
      - readme.md
      - .gitignore
      - .gitattribute
      - "**/*.md"
      - ".github/**"

pr:
  branches:
    include:
      - refs/heads/main
      - main
  paths:
    include:
      - PaymentService/**
    exclude:
      - readme.md
      - .gitignore
      - .gitattribute
      - "**/*.md"
      - ".github/**"

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: ../../shared/pipelines/variables/global-vars_v4.0.yaml
  - template: variables/project-vars.yaml

stages:
  - stage: BUILD
    displayName: "Build"
    jobs:
      - job: BuildInfra
        displayName: "Publish Job"
        steps:
          # Step 1: Log a simple message
          - task: Bash@3
            displayName: "Start Build and Publish Infra"
            inputs:
              targetType: "inline"
              script: |
                echo "Pipeline for PaymentService in infra-automation repo has started."
                echo "StaticWebsiteDomainNPE: $(StaticWebsiteDomainNPE)"
                echo "StaticWebsiteDomainPRD: $(StaticWebsiteDomainPRD)"
                echo "CustomDomainPrefix: $(CustomDomainPrefix)"
                echo "ResourceGroupNameSuffix: $(ResourceGroupNameSuffix)"
                echo "SvcAppStorageNameSuffix: $(SvcAppStorageNameSuffix)"
                echo "Authority: $(Authority)"
                echo "TfStateResourceGroupNameSuffix: $(TfStateResourceGroupNameSuffix)"
                echo "TfStateStorageNameSuffix: $(TfStateStorageNameSuffix)"
                echo "ApimFunctionKeyName: $(ApimFunctionKeyName)"
                echo "SvcAppStagingSlotName: $(SvcAppStagingSlotName)"
