trigger:
  batch: false
  branches:
    include:
      - refs/heads/main
      - main
  paths:
    include:
      - PaymentService/**
    exclude:
      - readme.md
      - .gitignore
      - .gitattribute
      - "**/*.md"
      - ".github/**"

pr:
  branches:
    include:
      - refs/heads/main
      - main
  paths:
    include:
      - PaymentService/**
    exclude:
      - readme.md
      - .gitignore
      - .gitattribute
      - "**/*.md"
      - ".github/**"

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: ../../shared/pipelines/variables/global-vars_v4.0.yaml
  - template: variables/project-vars.yaml

stages:
  - stage: BUILD
    displayName: "Build"
    pool:
      vmImage: windows-latest
    jobs:
      - job: BuildInfra
        displayName: "Publish Infra"
        steps:
          - template: ../../../shared/pipelines/templates/infra-build-tasks_v3.0.yaml
            parameters:
              artifactName: "$(InfraArtifactName)"
              fileCopyPattern: "$(InfraFileCopyPattern)"
